### ISSUE TITLE
Download my data ability for User 

### ISSUE THREAD

**Issue by luke-** [humhub/legal#20]
In many jurisdictions, online services are required to provide the ability to give Users and for held connected with them (with exceptions).

For example in UK a "Subject Access Request" under Freedom of Information, GDPR in Europe, and similar elsewhere.

Currently, there is no simple way for a user to make such a request, and even less of a means for an admin to provide that information easily.

The ideal way of confirming with this is to provide by default a "Download my data" button on User settings (which could be turned off in Admin settings). Other online platforms have similar functions.

(This would also assist in the event someone wishes to leave a community, close an account, or move jobs, but wishes to retain information held on them as they often have a right to.)

Original Issue: https://github.com/humhub/humhub/issues/4916

**Comment by samuk** [comment]
Is this issue actually resolved? I can't see anything in the WebUI or the legal tools module that enables users to download.

**Comment by luke-** [comment]
No there is no option for this yet

**Comment by samuk** [comment]
Ah thanks.

Is it a complicated bit of work?

**Comment by luke-** [comment]
@samuk Yes, this is mainly due to the large number of different contents and modules.

**Comment by funkycram** [comment]
I think we first need ActivityPub implementation to be able to export the data in a standard format. See https://github.com/humhub/humhub/issues/3150
Mastodon seems to have 2 formats: JSON for data at the ActivityPub format and CSV for the rest: https://docs.joinmastodon.org/user/moving/

**Comment by dantefromhell** [comment]
As this issue is about GDPR, this feature might affect the right to data portability (https://gdpr-info.eu/art-20-gdpr/) and  right to acces (https://gdpr-info.eu/art-15-gdpr/)

IMO there are 2 possible data-formats to consider (not mutually exclusive)
1) JSON as it's structured and can be taken anywhere with a custom importer
2) Raw SQL

From my limited code reading of HumHub I feel like
- JOSN has the benefit that it can be taken anywhere, but might provide limits to re-importability when a user decides to transfer from one HumHub provider to another (possible loss of information)

- SQL is easily importable into another HumHub instance but might require create issues when trying to move content to a different software (e.g. Fediverse)

Re-Reading the first message I am not sure which GDPR right the issue is trying to resolve. 15, 20 or both?

**Comment by samuk** [comment]
Any updates on this?

**Comment by funkycram** [comment]
If ActivityPub is not possible, other options would be:
- export JSON files using the REST API: possibility to reimport in another Humhub instances but not in other platforms
- export a PDF file of a stream (no import possibilities)
- generate an RSS feed

**Comment by samuk** [comment]
@luke- any updates on this please?

**Comment by luke-** [comment]
unfortunately not yet

**Comment by samuk** [comment]
@luke- what are your expectations for when this issue will be worked on? Is it high up in your backlog?

**Comment by luke-** [comment]
@samuk I'm afraid I don't know. It's not in our backlog for the near future, unfortunately.

**Comment by ArchBlood** [comment]
Here's an example controller that can be used;

### Example
Here in this example we create a JSON file with the profile & content data of the current user, then all you would have to do is create a view file for this controller action so that it can be downloaded, I picked JSON as it is easier to deal with and requires less external classes, we could also do an automatic download version if that were needed.
I'd like to note that the download time will very depending on how much data the user has generated through their profile and content made.
```php
<?php

namespace humhub\modules\legal\controllers;

use Yii;
use humhub\components\Controller;
use humhub\modules\user\models\Profile;
use humhub\modules\content\models\Content;

class ExportController extends Controller
{
    public function actionExport()
    {
        // Retrieve current user identity
        $userId = Yii::$app->user->identity;

        // Retrieve current user's profile information
        $profileData = Profile::findOne(['user_id' => $userId]);

        // Retrieve current user's content data (e.g., posts)
        $contentData = Content::find()->where(['created_by' => $userId])->all();

        // Combine profile and content data
        $userData = [
            'profile' => $profileData,
            'content' => $contentData
        ];

        // Convert data to JSON
        $jsonData = json_encode($userData, JSON_PRETTY_PRINT);

        // Set headers for file download
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        Yii::$app->response->headers->add('Content-Type', 'application/json');
        Yii::$app->response->headers->add('Content-Disposition', 'attachment; filename="userdata.json"');

        // Output JSON data to response body
        Yii::$app->response->content = $jsonData;
    }
}
```

**Comment by ArchBlood** [comment]
@luke- would you like a draft for a JSON download of user data?

**Comment by luke-** [comment]
@ArchBlood Thanks for the Draft PR.

I think we should create a generic content import/export interface, which we could then also use for the user data export

**Comment by ArchBlood** [comment]
> @ArchBlood Thanks for the Draft PR.
> 
> I think we should create a generic content import/export interface, which we could then also use for the user data export
>    

Thank you for the explanation, originally I thought the idea was to use the Restful API, which with this method uses the same idea.

**Comment by luke-** [comment]
Good point.

I'll have to think about that a bit. But basically there is nothing wrong with the user data export requiring the REST API module.

We would then have all the data definitions here.

**Comment by ArchBlood** [comment]
> Good point.
> 
> I'll have to think about that a bit. But basically there is nothing wrong with the user data export requiring the REST API module.
> 
> We would then have all the data definitions here.

Currently my only issue when it comes to dealing with "content" is that if an admin uses the download button it also exports all data from other modules that have a `contentcontainer_id` as well, example being the Custom Pages module, if an admin were to use the download button for their data, then the information from modules that an admin has generated will also be within the JSON data, "post" & "user" data works flawlessly, this method also makes it much easier to get any other data that a user generates.

My thoughts are, give the user an option to download their user-data that is within the `userdata.json` file, this method does not create a server-side file so this file is not stored anywhere other than residing only on the user's PC when downloaded so it is a secure method, it can not be accessed by other users, it is also setup so that only the current user (e.g. logged in user) gets their own information added to the `userdata.json`, this does not take into account impersonated users by an admin or who has the permission(s) it should then follow both the [User API](https://marketplace.humhub.com/module/rest/docs/html/user.html) & [Post API](https://marketplace.humhub.com/module/rest/docs/html/post.html) when it comes to the generated JSON file. I'm more than willing to keep it as a reference.
