### ISSUE TITLE
User Data Export - Enhancements

### ISSUE THREAD

**Issue by luke-** [humhub/legal#70]
Branch: `humhub-contrib:enh/data-export`

- [ ] Create Download as Background Job
	- [ ] Create ZIP file as ActiveJob and keep for X days 
	- [ ] If exist, show Download on "Export Data" Page
	- [ ] Send Notification once the Export Package is Ready
	- [ ] Include Files in ZIP (Optional?)
	  
- [ ] Create an Event allow other modules to Inject own Data. E.g. Polls
	- [ ] Create PRs for official modules
	- [ ] Inform "Marketplace Publisher" Space of new Event
	  
- [ ] Create Tests
- [ ] We should remove `post|polls|etc.content.comments` because it contains other users data.

Related: https://github.com/humhub-contrib/legal/issues/68#issuecomment-2003210782_

**Comment by ArchBlood** [comment]
We should update the following due to https://github.com/humhub-contrib/legal/pull/71/commits/bc220910fc8edeb3e1aea0df07b20b6a12ec4696
> We should remove post|polls|etc.content.comments because it contains other users data.

Currently the filter should filter out `content > comments > latest` but I've not tested for external modules, but I really recommend creating separate services, maybe we could even create a base class for this in the rest api?

**Comment by luke-** [comment]
@ArchBlood Thanks for your idea & prototype here. Here is the full PR: 
https://github.com/humhub/legal/pull/77
